server:
  port: 8081

spring:
  application:
    name: lab

  datasource:
    url: jdbc:postgresql://mi_banca_dev_2026:5432/mi_banca
    username: admin
    password: admin_2026
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka_server:29092 
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false